# Generated by Django 4.2.6 on 2023-10-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gains", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="sabor",
        ),
        migrations.AddField(
            model_name="produto",
            name="sabor",
            field=models.ManyToManyField(to="gains.sabor"),
        ),
    ]
