# Generated by Django 4.2.5 on 2023-10-17 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gains", "0002_remove_produto_sabor_produto_sabor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="sabor",
        ),
        migrations.DeleteModel(
            name="Sabor",
        ),
    ]
